---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - feature/*
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag

---
kind: secret
name: docker_username
data: Qq4pG4U/VmH9NP1pRVfm23/z3hq6TlXIUwqipWnLdewvj0YscjmBZmn0Lh94
---
kind: secret
name: docker_password
data: 86rDL/ZAzw5eKT3N6oddMo88jb8FBzz9GYLCSWoIJImOoLicCwDE8onHksV+rC0CZkc89/3fK7T0sRy28vLy8Q==
---
kind: signature
hmac: 2a78f38a304acf09c9bf2d63db47a97cd720db9cb323d5ffc0df1f155fc52f05

...
